[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "pandas",
    "dill",
    "torch",
    "torchvision",
    "torchaudio",
    "scipy",
    "torchaudio",
    "torchaudio",
    "torchaudio"
]
build-backend = "setuptools.build_meta"
